from django.urls import path
from . import views

urlpatterns = [
    path("site_admin/", views.site_admin, name="site_admin"),
    path("site_admin/dashboard", views.dashboard, name="dashboard"),

    path("site_admin/site_admin_festivals/", views.site_admin_festivals, name="site_admin_festivals"),
    path("site_admin/site_admin_schedule/", views.site_admin_schedule, name="site_admin_schedule"),
    path("site_admin/site_admin_dance_performers/", views.site_admin_dance_performers, name="site_admin_dance_performers"),
    path("site_admin/site_admin_musicians/", views.site_admin_musicians, name="site_admin_musicians"),
    path("site_admin/site_admin_emcees/", views.site_admin_emcees, name="site_admin_emcees"),
    path("site_admin/site_admin_food_vendors/", views.site_admin_food_vendors, name="site_admin_food_vendors"),
    path("site_admin/site_admin_tickets/", views.site_admin_tickets, name="site_admin_tickets"),
    path("site_admin/site_admin_orders/", views.site_admin_orders, name="site_admin_orders"),
    path("site_admin/site_admin_sponsors/", views.site_admin_sponsors, name="site_admin_sponsors"),
    path("site_admin/site_admin_volunteers/", views.site_admin_volunteers, name="site_admin_volunteers"),
    path("site_admin/site_admin_feedbacks/", views.site_admin_feedbacks, name="site_admin_feedbacks"),
    path("site_admin/site_admin_festival_images/", views.site_admin_festival_images, name="site_admin_festival_images"),

    path("site_admin/create_festival/", views.create_festival, name="create_festival"),
    path("site_admin/create_schedule/", views.create_schedule, name="create_schedule"),
    path("site_admin/create_dance_performer/", views.create_dance_performer, name="create_dance_performer"),
    path("site_admin/create_musician/", views.create_musician, name="create_musician"),
    path("site_admin/create_emcee/", views.create_emcee, name="create_emcee"),
    path("site_admin/create_food_vendor/", views.create_food_vendor, name="create_food_vendor"),
    path("site_admin/create_ticket/", views.create_ticket, name="create_ticket"),
    path("site_admin/create_order/", views.create_order, name="create_order"),
    path("site_admin/create_sponsor/", views.create_sponsor, name="create_sponsor"),
    path("site_admin/create_volunteer/", views.create_volunteer, name="create_volunteer"),
    path("site_admin/create_feedback/", views.create_feedback, name="create_feedback"),
    path("site_admin/create_festival_image/", views.create_festival_image, name="create_festival_image"),


    path("site_admin/edit_festival/<int:id>", views.edit_festival, name="edit_festival"),
    path("site_admin/edit_schedule/<int:id>", views.edit_schedule, name="edit_schedule"),
    path("site_admin/edit_dance_performer/<int:id>", views.edit_dance_performer, name="edit_dance_performer"),
    path("site_admin/edit_musician/<int:id>", views.edit_musician, name="edit_musician"),
    path("site_admin/edit_emcee/<int:id>", views.edit_emcee, name="edit_emcee"),
    path("site_admin/edit_food_vendor/<int:id>", views.edit_food_vendor, name="edit_food_vendor"),
    path("site_admin/edit_ticket/<int:id>", views.edit_ticket, name="edit_ticket"),
    path("site_admin/edit_order/<int:id>", views.edit_order, name="edit_order"),
    path("site_admin/edit_sponsor/<int:id>", views.edit_sponsor, name="edit_sponsor"),
    path("site_admin/edit_volunteer/<int:id>", views.edit_volunteer, name="edit_volunteer"),
    path("site_admin/edit_feedback/<int:id>", views.edit_feedback, name="edit_feedback"),
    path("site_admin/edit_festival_image/<int:id>", views.edit_festival_image, name="edit_festival_image"),


    path("site_admin/delete_festival/<int:id>", views.delete_festival, name="delete_festival"),
    path("site_admin/delete_schedule/<int:id>", views.delete_schedule, name="delete_schedule"),
    path("site_admin/delete_dance_performer/<int:id>", views.delete_dance_performer, name="delete_dance_performer"),
    path("site_admin/delete_musician/<int:id>", views.delete_musician, name="delete_musician"),
    path("site_admin/delete_emcee/<int:id>", views.delete_emcee, name="delete_emcee"),
    path("site_admin/delete_food_vendor/<int:id>", views.delete_food_vendor, name="delete_food_vendor"),
    path("site_admin/delete_ticket/<int:id>", views.delete_ticket, name="delete_ticket"),
    path("site_admin/delete_order/<int:id>", views.delete_order, name="delete_order"),
    path("site_admin/delete_sponsor/<int:id>", views.delete_sponsor, name="delete_sponsor"),
    path("site_admin/delete_volunteer/<int:id>", views.delete_volunteer, name="delete_volunteer"),
    path("site_admin/delete_feedback/<int:id>", views.delete_feedback, name="delete_feedback"),
    path("site_admin/delete_festival_image/<int:id>", views.delete_festival_image, name="delete_festival_image"),
]
