# Generated by Django 5.0 on 2024-02-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('ph_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('c_password', models.CharField(max_length=200)),
            ],
        ),
    ]
