# Generated by Django 5.0.2 on 2024-03-18 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_siteuser_managers_alter_siteuser_ph_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='ph_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in the form: 9800000000', regex='(\\+977)?[9][6-9]\\d{8}')]),
        ),
    ]
