# Generated by Django 5.0.2 on 2024-04-10 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_siteuser_ph_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='password',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Password must have a minimum of 8 characters and a maximum of 16, and should contain at least 1 Capital Letter, 1 Number, and 1 Special Character.', regex='^(?=.*[A-Z])(?=.*\\d)(?=.*[^\\w\\s]).{8,16}$')]),
        ),
    ]
