# Generated by Django 5.0.2 on 2024-04-11 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salsa_Festival', '0003_feedback_alter_sponsor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
    ]
