# Generated by Django 5.0.2 on 2024-04-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salsa_Festival', '0004_remove_feedback_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
