# Generated by Django 5.0.2 on 2024-04-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salsa_Festival', '0005_alter_volunteer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='id',
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='email',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
