# Generated by Django 5.0.2 on 2024-04-11 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salsa_Festival', '0006_remove_sponsor_id_remove_volunteer_id_and_more'),
        ('festivals', '0015_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='festival',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='festivals.festival'),
            preserve_default=False,
        ),
    ]
