# Generated by Django 5.0.2 on 2024-04-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salsa_Festival', '0007_feedback_festival'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='images',
            field=models.ImageField(default=None, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
