# Generated by Django 5.0.2 on 2024-04-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salsa_Festival', '0008_sponsor_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='images',
            new_name='feature_image',
        ),
    ]
