# Generated by Django 5.0.2 on 2024-04-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salsa_Festival', '0009_rename_images_sponsor_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
