# Generated by Django 5.0.2 on 2024-04-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salsa_Festival', '0010_sponsor_id_alter_sponsor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='feature_image',
            field=models.ImageField(upload_to='uploads/djangodbmodelsfieldscharfield'),
        ),
    ]
