# Generated by Django 5.0.2 on 2024-04-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salsa_Festival', '0013_alter_sponsor_email_alter_volunteer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='last_name',
        ),
    ]
