# Generated by Django 5.0.2 on 2024-04-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salsa_Festival', '0014_remove_feedback_first_name_remove_feedback_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='first_name',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='last_name',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
