# Generated by Django 5.0 on 2024-03-09 17:52

import django.db.models.deletion
import festivals.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BillUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='festivals.bill')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('description', models.CharField(max_length=1000)),
                ('past_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('feature_image', models.ImageField(null=True, upload_to='uploads/djangodbmodelsfieldscharfield', verbose_name='Festival')),
                ('location', models.CharField(max_length=255, null=True)),
                ('is_next', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emcees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(null='True', upload_to=festivals.models.get_image_file, verbose_name='Emcees')),
                ('festival', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='festivals.festival')),
            ],
        ),
        migrations.CreateModel(
            name='DancePerformers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('act', models.CharField(max_length=255)),
                ('image', models.ImageField(null='True', upload_to=festivals.models.get_image_file, verbose_name='Dance Image')),
                ('festival', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='festivals.festival')),
            ],
        ),
        migrations.CreateModel(
            name='FestivalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=festivals.models.get_image_file, verbose_name='Image')),
                ('image_title', models.CharField(max_length=255, null='True')),
                ('festival', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='festivals.festival')),
            ],
        ),
        migrations.CreateModel(
            name='FoodVendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(null='True', upload_to=festivals.models.get_image_file, verbose_name='FoodVendors')),
                ('festival', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='festivals.festival')),
            ],
        ),
        migrations.CreateModel(
            name='Musicians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('act', models.CharField(max_length=255)),
                ('image', models.ImageField(null='True', upload_to=festivals.models.get_image_file, verbose_name='Musicians')),
                ('festival', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='festivals.festival')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(default='Regular', max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivals.festival')),
            ],
        ),
    ]
