# Generated by Django 5.0.2 on 2024-03-18 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0005_remove_order_tickets_remove_ticket_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ticket',
            new_name='ticket_amount',
        ),
    ]
