# Generated by Django 5.0.2 on 2024-03-18 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0006_rename_ticket_order_ticket_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketamount',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivals.ticket'),
        ),
    ]
