# Generated by Django 5.0.2 on 2024-03-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0007_alter_ticketamount_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ticket_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='ticket_amounts',
            field=models.ManyToManyField(related_name='orders', to='festivals.ticketamount'),
        ),
    ]
