# Generated by Django 5.0.2 on 2024-03-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0009_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
