# Generated by Django 5.0.2 on 2024-04-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0011_ticket_max_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='max_amount',
            new_name='max_no_tickets',
        ),
        migrations.AddField(
            model_name='ticket',
            name='sold_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
