# Generated by Django 5.0.2 on 2024-04-02 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0012_rename_max_amount_ticket_max_no_tickets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('act', models.CharField(max_length=255)),
                ('festival', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='festivals.festival')),
            ],
        ),
    ]
