# Generated by Django 5.0.2 on 2024-04-02 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0013_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivals.festival'),
        ),
    ]
