# Generated by Django 5.0.2 on 2024-04-11 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0015_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='order_name',
            field=models.SlugField(default=''),
        ),
    ]
