# Generated by Django 5.0.2 on 2024-04-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0016_order_order_date_order_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
