# Generated by Django 5.0.2 on 2024-04-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0017_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='festival',
            name='past_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
